# application.yml 
---
spring:
  application:
    name: recensioni-seguite
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        # configurazione per effettuare esprimenti, NON USARE UN PRODUZIONE
        # dopo quanto tempo consul deve smettere di restituire servizi che non rispondono all'health check?
        healthCheckCriticalTimeout: 45s
        # consul deve restituire solo servizi che passano l'health check (default=false)
        queryPassing: true
    loadbalancer:
      ribbon.enabled: false
  datasource:
    url: jdbc:postgresql://recensioneseguitedb:5432/recensioniseguite
    username: postgres
    password: postgres
server: 
  port: 8080
#  port: 8080
  # per swagger, se dietro a un api gateway 
  forward-headers-strategy: framework

# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false
spring.jpa.hibernate.ddl-auto: create
# KAFKA CONSUMER

